// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

RWTexture2D<float4> Dst;

Texture2D Source;

float widthScale;
float heightScale;

[numthreads(1,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{

	uint x = ceil(id.x/widthScale); 
	uint y = ceil(id.y/heightScale); 

	 Dst[id.xy]= Source[uint2(x,y)];
}
